// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

/* eslint-disable */
import en from './en'
import { initFormatters } from './formatters'
import fr from './fr'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslations = {
  en,
  fr,
}

export const loadLocale = (locale: Locales) => {
  if (loadedLocales[locale]) return

  loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
  loadFormatters(locale)
}

export const loadAllLocales = () => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales) => {
  loadedFormatters[locale] = initFormatters(locale)
}
